name: 'Continuous Delivery'

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: model-api-challenge
  GAR_LOCATION: us-central1
  REPOSITORY: model-api-repo
  SERVICE: model-api
  VERSION: v1
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud Credentials
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for GCP
        run: |
          gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build --build-arg MODEL_VERSION=${VERSION}.0 -t $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:$VERSION .

      - name: Push Docker image to Artifact Registry
        run: |
          docker push $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:$VERSION

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE \
            --image $GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:$VERSION \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated